### ISSUE TITLE
Provider review continued (February 16, 2018)

### ISSUE THREAD

**Issue by catsby** [f5devcentral/terraform-provider-bigip-old#59]
Almost there! 

For acceptance tests that create actual resources in a test environment, it’s important that the test name match the pattern “TestAcc”. The `testacc` task in the Makefile needs to be updated to test `TF_ACC=1`. See the [GNUmakefile in the AWS Provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/GNUmakefile#L17) as a reference. The environment variable `TF_ACC` is set so that the testing framework knows to allow network connections. By setting this environment variable, the testing framework will only run tests that have the naming pattern starting with `TestAcc`. 

For example, test [`TestBigipCmDevice_create`](https://github.com/f5devcentral/terraform-provider-bigip/blob/master/bigip/resource_bigip_cm_device_test.go#L25) should be named `TestAccBigipCmDevice_create`. I’ve open a Pull Request here with some suggested modifications, and some questions: 

- https://github.com/f5devcentral/terraform-provider-bigip/pull/57

Please add a `stable-website` branch to the repository. This branch is used for deploying documentation. As a practice, new features and documentation are sent via pull requests and merged into master. The `website` folder on the `stable-website` branch should always contain documentation that reflects the *current version of the provider*. If new features are added, or additional documentation that is not yet released in a version of the provider, then said docs are not merged into `stable-website`. Any documentation updates that are merged that do apply to the currently released version, should be cherry-picked over to `stable-website` so that we can redeploy the website and update the content without deploying a new version of the Provider binary. 

As a best practice, the CREATE method of any Resource should at least return the results of it’s own READ method. In certain cases it may need to return the results of the UPDATE method, depending on if the CREATE method is capable of setting all possible configuration values. If for example the API call to create Resource only allows basic creation, the remaining configuration is applied via update, then CREATE should return UPDATE, and UPDATE should return READ. [AWS Security Group Resource](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_security_group.go) is an example of this; the CREATE only allows creating a Security Group with a name and description, and we must make other API calls to apply the rules. Thus, CREATE returns the results of UPDATE. 

UPDATE methods should always return the results of the READ method. 

For resources like `resource_bigip_cm_device`, resourceBigipCmDeviceCreate should return the results of `resourceBigipCmDeviceRead`. `resourceBigipCmDeviceUpdate` should check the error returned by `client.ModifyDevice(r)`, and then return `resourceBigipCmDeviceRead`.

- https://github.com/f5devcentral/terraform-provider-bigip/blob/master/bigip/resource_bigip_cm_device.go

In `resource_bigip_ltm_pool`, it seems `nodes` and `monitors` are not being read back from the API and saved to state. Is this by design?

- https://github.com/f5devcentral/terraform-provider-bigip/blob/8b7e5507c8d8c642eac3e7e3ebc0156fc1f967b8/bigip/resource_bigip_ltm_pool.go#L127-L133

When reading non-scalar data back from the API and storing to state, we need to check the error returned from `d.Set` and log any errors. Example here are `search` and `name_servers`, both `TypeSet` attributes. It’s possible that the values returned from the API are not in the proper format to be stored into state as a `TypeSet`, in which case without error handling the user will have no information why there’s a mismatch between state and value in the API. An example here is `name_servers` and `search` here:

- https://github.com/f5devcentral/terraform-provider-bigip/blob/8b7e5507c8d8c642eac3e7e3ebc0156fc1f967b8/bigip/resource_bigip_sys_dns.go#L113-L115

Here’s an example of the error checking. Returning an error here is not required, but you should at least log out that there was an error attempting to save:

- https://github.com/terraform-providers/terraform-provider-aws/blob/397669f8a2040bac3e714732193966d160edbf96/aws/resource_aws_rds_cluster.go#L612-L614

**Comment by scshitole** [comment]
@catsby 
Added TestAcc for the test files and ran the tests
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ BIGIP_USER=admin BIGIP_PASSWORD=admin BIGIP_HOST=10.192.74.73 TF_ACC=1  go test ./bigip -v  -run=TestAccBigip
=== RUN   TestAccBigipCmDevice_create
--- PASS: TestAccBigipCmDevice_create (2.38s)
=== RUN   TestAccBigipCmDevice_import
--- PASS: TestAccBigipCmDevice_import (3.30s)
=== RUN   TestAccBigipCmDevicegroup_create
--- PASS: TestAccBigipCmDevicegroup_create (3.39s)
=== RUN   TestAccBigipCmDevicegroup_import
--- PASS: TestAccBigipCmDevicegroup_import (3.12s)
=== RUN   TestAccBigipLtmIRule_create
--- PASS: TestAccBigipLtmIRule_create (3.09s)
=== RUN   TestAccBigipLtmIRule_import
--- PASS: TestAccBigipLtmIRule_import (2.82s)
=== RUN   TestAccBigipLtmMonitor_create
--- PASS: TestAccBigipLtmMonitor_create (5.06s)
=== RUN   TestAccBigipLtmMonitor_import
--- PASS: TestAccBigipLtmMonitor_import (4.68s)
=== RUN   TestAccBigipLtmNode_create
--- PASS: TestAccBigipLtmNode_create (2.57s)
=== RUN   TestAccBigipLtmNode_import
--- PASS: TestAccBigipLtmNode_import (3.23s)
=== RUN   TestAccBigipLtmNodeInvalid
--- PASS: TestAccBigipLtmNodeInvalid (0.01s)
=== RUN   TestAccBigipLtmNodeCreate
--- PASS: TestAccBigipLtmNodeCreate (0.02s)
=== RUN   TestAccBigipLtmPersistenceProfileCookieCreate
--- PASS: TestAccBigipLtmPersistenceProfileCookieCreate (3.13s)
=== RUN   TestAccBigipLtmPersistenceProfileCookieImport
--- PASS: TestAccBigipLtmPersistenceProfileCookieImport (2.82s)
=== RUN   TestAccBigipLtmPersistenceProfileDstAddrCreate
--- PASS: TestAccBigipLtmPersistenceProfileDstAddrCreate (3.38s)
=== RUN   TestAccBigipLtmPersistenceProfileDstAddrImport
--- PASS: TestAccBigipLtmPersistenceProfileDstAddrImport (3.53s)
=== RUN   TestAccBigipLtmPersistenceProfileSrcAddrCreate
--- PASS: TestAccBigipLtmPersistenceProfileSrcAddrCreate (2.69s)
=== RUN   TestAccBigipLtmPersistenceProfileSrcAddrImport
--- PASS: TestAccBigipLtmPersistenceProfileSrcAddrImport (3.31s)
=== RUN   TestAccBigipLtmPersistenceProfileSSLCreate
--- PASS: TestAccBigipLtmPersistenceProfileSSLCreate (3.51s)
=== RUN   TestAccBigipLtmPersistenceProfileSSLImport
--- PASS: TestAccBigipLtmPersistenceProfileSSLImport (2.69s)
=== RUN   TestAccBigipLtmPool_create
--- PASS: TestAccBigipLtmPool_create (5.02s)
=== RUN   TestAccBigipLtmPool_import
--- PASS: TestAccBigipLtmPool_import (6.89s)
=== RUN   TestAccBigipLtmfasthttp_create
--- PASS: TestAccBigipLtmfasthttp_create (6.48s)
=== RUN   TestAccBigipLtmProfilefasthttp_import
--- PASS: TestAccBigipLtmProfilefasthttp_import (7.00s)
=== RUN   TestAccBigipLtmProfileFastl4_create
--- PASS: TestAccBigipLtmProfileFastl4_create (3.86s)
=== RUN   TestAccBigipLtmProfileFastl4_import
--- PASS: TestAccBigipLtmProfileFastl4_import (2.71s)
=== RUN   TestAccBigipLtmProfileHttp2_create
--- PASS: TestAccBigipLtmProfileHttp2_create (3.26s)
=== RUN   TestAccBigipLtmProfileHttp2_import
--- PASS: TestAccBigipLtmProfileHttp2_import (2.97s)
=== RUN   TestAccBigipLtmProfileHttpcompress_create
--- PASS: TestAccBigipLtmProfileHttpcompress_create (3.63s)
=== RUN   TestAccBigipLtmProfileHttpcompress_import
--- PASS: TestAccBigipLtmProfileHttpcompress_import (2.38s)
=== RUN   TestAccBigipLtmProfileoneconnect_create
--- PASS: TestAccBigipLtmProfileoneconnect_create (3.45s)
=== RUN   TestAccBigipLtmProfileoneconnect_import
--- PASS: TestAccBigipLtmProfileoneconnect_import (3.33s)
=== RUN   TestAccBigipLtmProfileTcp_create
--- PASS: TestAccBigipLtmProfileTcp_create (2.51s)
=== RUN   TestAccBigipLtmProfileTcp_import
--- PASS: TestAccBigipLtmProfileTcp_import (3.23s)
=== RUN   TestAccBigipLtmsnat_create
--- PASS: TestAccBigipLtmsnat_create (3.36s)
=== RUN   TestAccBigipLtmsnat_import
--- PASS: TestAccBigipLtmsnat_import (2.39s)
=== RUN   TestAccBigipLtmsnatpool_create
--- PASS: TestAccBigipLtmsnatpool_create (3.41s)
=== RUN   TestAccBigipLtmsnatpool_import
--- PASS: TestAccBigipLtmsnatpool_import (3.41s)
=== RUN   TestAccBigipLtmVA_create
--- PASS: TestAccBigipLtmVA_create (3.21s)
=== RUN   TestAccBigipLtmVA_import
--- PASS: TestAccBigipLtmVA_import (2.50s)
=== RUN   TestAccBigipLtmVS_create
--- PASS: TestAccBigipLtmVS_create (4.14s)
=== RUN   TestAccBigipLtmVS_import
--- PASS: TestAccBigipLtmVS_import (4.20s)
=== RUN   TestAccBigipNetroute_create
--- PASS: TestAccBigipNetroute_create (3.36s)
=== RUN   TestAccBigipNetroute_import
--- PASS: TestAccBigipNetroute_import (3.31s)
=== RUN   TestAccBigipNetselfip_create
--- PASS: TestAccBigipNetselfip_create (3.05s)
=== RUN   TestAccBigipNetselfip_import
--- PASS: TestAccBigipNetselfip_import (3.16s)
=== RUN   TestAccBigipLtmvlan_create
--- PASS: TestAccBigipLtmvlan_create (2.81s)
=== RUN   TestAccBigipLtmvlan_import
--- PASS: TestAccBigipLtmvlan_import (3.04s)
=== RUN   TestAccBigipSysdns_create
--- PASS: TestAccBigipSysdns_create (2.99s)
=== RUN   TestAccBigipSysdns_import
--- PASS: TestAccBigipSysdns_import (3.14s)
=== RUN   TestAccBigipSysIapp_create
--- PASS: TestAccBigipSysIapp_create (3.25s)
=== RUN   TestAccBigipSysIapp_import
--- PASS: TestAccBigipSysIapp_import (3.08s)
=== RUN   TestAccBigipSysNtp_create
--- PASS: TestAccBigipSysNtp_create (3.06s)
=== RUN   TestAccBigipSysNtp_import
--- PASS: TestAccBigipSysNtp_import (3.04s)
=== RUN   TestAccBigipSysNtpInvalid
--- PASS: TestAccBigipSysNtpInvalid (0.00s)
=== RUN   TestAccBigipSysProvision_create
--- PASS: TestAccBigipSysProvision_create (2.92s)
=== RUN   TestAccBigipSysProvision_import
--- PASS: TestAccBigipSysProvision_import (3.01s)
=== RUN   TestAccBigipSyssnmp_create
--- PASS: TestAccBigipSyssnmp_create (3.05s)
=== RUN   TestAccBigipSyssnmp_import
--- PASS: TestAccBigipSyssnmp_import (3.30s)
PASS
ok  	github.com/f5devcentral/terraform-provider-bigip/bigip	195.889s

**Comment by scshitole** [comment]
@catsby
Please add a stable-website branch to the repository.

Created  branch stable-website

https://github.com/f5devcentral/terraform-provider-bigip/tree/stable-website

**Comment by scshitole** [comment]
@catsby 
updated all resources with read for create and update with error correction

**Comment by scshitole** [comment]
@catsby 
In resource_bigip_ltm_pool, it seems nodes and monitors are not being read back from the API and saved to state. Is this by design?
nodes and monitors are added back to the API, it was disabled while troubleshooting, added back

**Comment by catsby** [comment]
Hey @scshitole – in #57 I noted that running `make testacc` with no environment variables causes a panic, were you able to reproduce that?

**Comment by scshitole** [comment]
@catsby 
yes I was able to reproduce the same
BIGIP_USER=admin BIGIP_PASSWORD=admin BIGIP_HOST=10.192.74.73 TF_ACC=1 go test ./bigip -v -run=TestAcc
=== RUN   TestAccBigipCmDevice_create
--- FAIL: TestAccBigipCmDevice_create (60.01s)
	testing.go:513: Step 0 error: Error planning: 1 error occurred:
		
		* provider.bigip: Get https://10.192.74.73/mgmt/tm/net/self: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
panic: interface conversion: interface {} is nil, not *bigip.BigIP [recovered]
	panic: interface conversion: interface {} is nil, not *bigip.BigIP

**Comment by catsby** [comment]
I'm running the following:

```
[terraform-provider-bigip][master](3)$ BIGIP_USER=admin BIGIP_PASSWORD=admin BIGIP_HOST=10.192.74.73 TF_ACC=1 go test ./bigip -v -run=TestAccBigip 
=== RUN   TestAccBigipCmDevice_create
--- FAIL: TestAccBigipCmDevice_create (60.02s)
        testing.go:513: Step 0 error: Error planning: 1 error occurred:

                * provider.bigip: Get https://10.192.74.73/mgmt/tm/net/self: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
panic: interface conversion: interface {} is nil, not *bigip.BigIP [recovered]
        panic: interface conversion: interface {} is nil, not *bigip.BigIP

goroutine 6 [running]:
testing.tRunner.func1(0xc4202bcb40)
        /Users/clint/.goenv/versions/1.9.3/src/testing/testing.go:711 +0x2d2
panic(0x18ede80, 0xc420331ac0)
        /Users/clint/.goenv/versions/1.9.3/src/runtime/panic.go:491 +0x283
github.com/f5devcentral/terraform-provider-bigip/bigip.testCheckdevicesDestroyed(0xc4203fa420, 0xc4203fa720, 0x0)
        /Users/clint/Projects/Go/src/github.com/f5devcentral/terraform-provider-bigip/bigip/resource_bigip_cm_device_test.go:87 +0x272
github.com/f5devcentral/terraform-provider-bigip/vendor/github.com/hashicorp/terraform/helper/resource.testStep(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/clint/Projects/Go/src/github.com/f5devcentral/terraform-provider-bigip/vendor/github.com/hashicorp/terraform/helper/resource/testing_config.go:77 +0xd13
github.com/f5devcentral/terraform-provider-bigip/vendor/github.com/hashicorp/terraform/helper/resource.Test(0x1f37aa0, 0xc4202bcb40, 0x0, 0xc420215430, 0xc420288f90, 0x0, 0x0, 0x1a1c568, 0xc4201b2420, 0x1, ...)
        /Users/clint/Projects/Go/src/github.com/f5devcentral/terraform-provider-bigip/vendor/github.com/hashicorp/terraform/helper/resource/testing.go:571 +0xae8
github.com/f5devcentral/terraform-provider-bigip/bigip.TestAccBigipCmDevice_create(0xc4202bcb40)
        /Users/clint/Projects/Go/src/github.com/f5devcentral/terraform-provider-bigip/bigip/resource_bigip_cm_device_test.go:26 +0x396
testing.tRunner(0xc4202bcb40, 0x1a1bde8)
        /Users/clint/.goenv/versions/1.9.3/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /Users/clint/.goenv/versions/1.9.3/src/testing/testing.go:789 +0x2de
exit status 2
FAIL    github.com/f5devcentral/terraform-provider-bigip/bigip  60.048s

```

The address `10.192.74.73` doesn't seem to be an address that I can reach.

**Comment by scshitole** [comment]
@catsby 
Still checking why its giving 'panic'  meanwhile if you need access to BIG-IP you can use the below
BIGIP_USER=admin BIGIP_PASSWORD=cisco123 BIGIP_HOST=13.56.242.22  TF_ACC=1   go test ./bigip -v  -run=Test*
=== RUN   TestAccProvider
--- PASS: TestAccProvider (0.00s)
=== RUN   TestAccBigipCmDevice_create
--- PASS: TestAccBigipCmDevice_create (0.48s)
=== RUN   TestAccBigipCmDevice_import
--- PASS: TestAccBigipCmDevice_import (3.84s)

**Comment by scshitole** [comment]
@catsby I'm running the following:

I fixed the 'panic' issue, tried with a fake address please see below
BIGIP_USER=admin BIGIP_PASSWORD=admin BIGIP_HOST=10.19.77.11  TF_ACC=1 go test ./bigip -v -run=TestAccBigip 
=== RUN   TestAccBigipCmDevice_create
+++++++++++++++    Get https://10.19.77.11/mgmt/tm/net/self: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
exit status 1
FAIL	github.com/f5devcentral/terraform-provider-bigip/bigip	60.131s
SJC-ML-SHITOLE:terraform-provider-bigip shitole$

**Comment by scshitole** [comment]
@catsby 
Added the required error logging please review and let us know next steps.

**Comment by catsby** [comment]
Hey there – the items I've listed above (as well as items from previous reviews) are specific examples of things I see throughout the codebase. While I see the specific ones may have been addressed, they represent issues that I see in other resources as well. I'm still seeing a handful of methods unimplemented or with large chunks of code commented out, resource attributes not being read from API and saved to state, and non-scalar attributes being saved to state without error checking.

Please review the codebase for these patterns and make the necessary changes. 

In the specific case of `sys_dns`:

https://github.com/f5devcentral/terraform-provider-bigip/blob/70833c00e6b8c1617b58beb34d9d19c98e0bb0c4/bigip/resource_bigip_sys_dns.go#L117-L130

`name_servers`, `search` and `numberof_dots` are having `d.Set` called twice now, one without error checking, and one with. `numberof_dots` is a scalar attribute and does not require error checking. 

About `numberof_dots`: 

- What is the function of this attribute? [The Documentation](https://github.com/f5devcentral/terraform-provider-bigip/blob/master/website/docs/r/bigip_sys_dns.html.markdown) says to "Provide the number 2". Is this something users can change? 
- Please also consider renaming this attribute to `number_of_dots`.

**Comment by scshitole** [comment]
@catsby 
thanks will look at each of the resource again and make changes accordingly 
func resourceBigipSysDnsRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*bigip.BigIP)

	description := d.Id()

	log.Println("[INFO] Reading DNS " + description)

	dns, err := client.DNSs()
	if err != nil {
		return err
	}
	if dns == nil {
		log.Printf("[WARN] DNS (%s) not found, removing from state", d.Id())
		d.SetId("")
		return nil
	}
	d.Set("description", dns.Description)

	if err := d.Set("name_servers", dns.NameServers); err != nil {
		return fmt.Errorf("[DEBUG] Error saving Name Servers to state for DNS (%s): %s", d.Id(), err)
	}

	d.Set("number_of_dots", dns.NumberOfDots)

	if err := d.Set("search", dns.Search); err != nil {
		return fmt.Errorf("[DEBUG] Error saving Search  to state for DNS (%s): %s", d.Id(), err)
	}

	return nil
}

**Comment by scshitole** [comment]
@catsby  hi Clint, can you please quickly check if anything else missing .

**Comment by bodgit** [comment]
As a prospective user of this provider, I've noticed that the `vendor/` directory particularly the `go-bigip` library is getting changes committed directly to it rather than being committed to the upstream repository and subsequently updated with `govendor`.

This means the library code is diverging and it's going to end up a mess. If I removed all of the vendored libraries and re-ran `govendor` I'd end up with [this commit](https://github.com/f5devcentral/go-bigip/commit/6a067faa1ac43f925d0b5374dae95ccb1a6b4fb0) which is from December 9th and would lose all of the local changes since.

**Comment by paultyng** [comment]
:wave: Clint is out of the office this week, so I am following up on some things while he is away.

The issue mentioned above from @bodgit does need to be addressed on this repo. The vendor directory must be managed / updated by `govendor`.

I noticed you also had some `...Exists` methods that were not hooked up, they should either be removed or used in the resources:

```
bigip/resource_bigip_ltm_snat.go:151:6: func resourceBigipLtmSnatExists is unused (U1000)
bigip/resource_bigip_net_selfip.go:92:6: func resourceBigipNetSelfIPExists is unused (U1000)
bigip/resource_bigip_net_vlan.go:124:6: func resourceBigipNetVlanExists is unused (U1000)
```

There are also a few places in the code where you have an `err` returned but never check `err != nil`:

https://github.com/f5devcentral/terraform-provider-bigip/blob/98b1130b767e17e28ff0067d5447dce6e592e4a1/bigip/resource_bigip_ltm_persistence_profile_cookie.go#L154-L159

There are others as well, so I could confirm you are always checking the `err` value.

`switch` in Go does not need a `break`:

https://github.com/f5devcentral/terraform-provider-bigip/blob/98b1130b767e17e28ff0067d5447dce6e592e4a1/bigip/validators.go#L35-L50

By the way I found many of these using [gometalinter](https://github.com/alecthomas/gometalinter) which may be a useful too to help find some of these problems in the code earlier, it can integrate with many editors.

**Comment by paultyng** [comment]
It seems besides the `...Exists` methods you also have some `CheckDestroy` and `ValidateFunc` commented out in various files, if those shouldn't be used, please delete the line, if they should be used, please uncomment.

**Comment by paultyng** [comment]
For importers that are just passing the ID through to the state, you can just use:

https://github.com/hashicorp/terraform/blob/351c6bed79abbb40e461d3f7d49fe4cf20bced41/helper/schema/resource_importer.go#L50

Instead of doing: 

https://github.com/f5devcentral/terraform-provider-bigip/blob/98b1130b767e17e28ff0067d5447dce6e592e4a1/bigip/resource_bigip_ltm_profile_tcp.go#L205-L207

**Comment by paultyng** [comment]
These two fields are passed to this SDK method, but the SDK doesn't do anything with them?

https://github.com/f5devcentral/terraform-provider-bigip/blob/98b1130b767e17e28ff0067d5447dce6e592e4a1/bigip/resource_bigip_ltm_virtual_server.go#L185-L186

It also seems weird to have two boolean values that are the opposite of each other?

**Comment by scshitole** [comment]
@paultyng thanks for reviewing will update you soon.

**Comment by scshitole** [comment]
@bodgit I have updated https://github.com/f5devcentral/go-bigip with the latest stuff from vendor and hence forth I am not making direct changes to vendor only through govendor

**Comment by bodgit** [comment]
Is there any particular reason https://github.com/f5devcentral/go-bigip has diverged from the original https://github.com/scottdware/go-bigip ? Seems like a lot of effort to maintain a fork of the library especially as it still seems to be actively maintained.

**Comment by scshitole** [comment]
@bodgit some background here https://github.com/scottdware/go-bigip/issues/45

**Comment by fatmcgav** [comment]
I just happened to click through to this issue whilst looking at scottdware/go-bigip, and then found the following F5 Go lib linked on Devcentral: https://github.com/e-XpertSolutions/f5-rest-client
Source: https://devcentral.f5.com/codeshare/go-library-to-manage-big-ip-icontrol-rest-api-925?tag=icontrolrest

Might be worth a review...

**Comment by scshitole** [comment]
These two fields are passed to this SDK method, but the SDK doesn't do anything with them?

@paultyng 
They are being used by SDK

      ```VlansEnabled        bool      `json:"vlansEnabled,omitempty"`
	   VlansDisabled       bool      `json:"vlansDisabled,omitempty"`
```
https://github.com/f5devcentral/terraform-provider-bigip/blob/master/vendor/github.com/f5devcentral/go-bigip/ltm.go

**Comment by scshitole** [comment]
@paultyng 
For importers that are just passing the ID through to the state, you can just use:
schema.ImportStatePassThrough
-->Updated all the resources with the above  and removed unwanted methods

It seems besides the ...Exists methods you also have some CheckDestroy and ValidateFunc commented out in various files, .....
--> Updated all the resources and removed unwanted commented CheckDestroy, Validatefunc and exits.

**Comment by adam-f5** [comment]
Repository Archived
